### PR TITLE
If the platform is darwin put the title bar buttons on the left

### LINKED ISSUE #36: On macOS, QMainWindow window buttons appear on wrong side of title bar
On macOS, the window's close, minimize, and maximize buttons appear on the right side of the title bar when they should be appearing on the left side.

### PR DESCRIPTION
**Pull request by Jerakin**
Fixes https://github.com/gmarull/qtmodern/issues/36

### CODE REVIEW

**Comment by gmarull** [comment]
Thanks @Jerakin . Would you like to become a maintainer of this repository :-) ?

**Comment by Jerakin** [comment]
That would be awesome, could you also take the time and add me as a maintainer at https://pypi.org/project/qtmodern/ (username: jerakin) ? So I can do pypi releases too :)

**Comment by gmarull** [comment]
@Jerakin Done.

You may also be interested in a better approach regarding custom titlebars. I have gathered all necessary bits here https://gist.github.com/gmarull/75a7f67bd1944bc59141f31a46c80591 (haven't tested the gist, but should work). The advantage is that all native functionality is preserved (e.g. AeroSnap on Windows). The end result is something like this:

Windows:
image

macOS:
image

**Comment by Jerakin** [comment]
Very interesting, as this is not using `Qt.FramelessWindowHint` I think it will also make the minimize button work.

**Comment by razaqq** [comment]
I know this has nothing to do with the topic, but can I find the code for that vertical sidebar anywhere? Looks really good @gmarull

**Pull request merged**
